export const products = [
  {
      id: 1,
      name: 'Wireless Earbuds',
      href: '#',
      imageSrc: 'https://imgs.search.brave.com/mCV1KwjEKy3iSQ5JxGOWkK83N3-f2wa7FJ4e_T0e7t8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9iMmMt/Y29udGVudGh1Yi5j/b20vd3AtY29udGVu/dC91cGxvYWRzLzIw/MjMvMDMvTG9naXRl/Y2gtWm9uZS1XaXJl/bGVzcy1FYXJidWRz/LmpwZz9xdWFsaXR5/PTUwJnN0cmlwPWFs/bA',
      imageAlt: "Wireless Earbuds in black.",
      price: '$99',
      color: 'Black',
  },
  {
      id: 2,
      name: 'Bluetooth Speaker',
      href: '#',
      imageSrc: 'https://imgs.search.brave.com/gDj0yu-cw5M4MUCQKybl6jDZG4if31U-RCfF6ra8OiQ/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/c2hvcGlmeS5jb20v/cy9maWxlcy8xLzA1/MTcvMjE5OS80NDMy/L2ZpbGVzLzIwMjQw/MzI2LTE0MTgxNC5q/cGc_dj0xNzExNDM0/MzA2',
      imageAlt: "Portable Bluetooth Speaker.",
      price: '$79',
      color: 'Black',
  },
  {
      id: 3,
      name: 'Gaming Mouse',
      href: '#',
      imageSrc: 'https://imgs.search.brave.com/exzwRMrAAQxoGCr7woz1X4WrlwelzIeiTBn2PStafuI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jMS5u/ZXdlZ2dpbWFnZXMu/Y29tL3Byb2R1Y3Rp/bWFnZS9uYjMwMC9B/TVpXUzIzMDQxMDBJ/MVk0M0I1LmpwZw',
      imageAlt: "Ergonomic Gaming Mouse.",
      price: '$49',
      color: 'RGB',
  },
  {
      id: 4,
      name: '4K Ultra HD Monitor',
      href: '#',
      imageSrc: 'https://imgs.search.brave.com/mO7wWQTi_AHYsEzvIHLwiZda-x0vqs9aiXGTkC6vV1c/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFoakVTT2pRVEwu/anBn',
      imageAlt: "27-inch 4K Ultra HD Monitor.",
      price: '$399',
      color: 'White',
  },
  {
      id: 5,
      name: 'Mechanical Keyboard',
      href: '#',
      imageSrc: 'https://imgs.search.brave.com/g8P4XFWKZdXRJcZFjcWKC-q9nWryWbiY7W1JjZ2Ap-g/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jbGFy/a2RlYWxzLmNvbS93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyNC8x/MC9NU0ktRm9yZ2Ut/R0szMDAtUkdCLW1l/Y2hhbmljYWwta2V5/Ym9hcmQtYW5kLW1v/dXNlLTUzNng1MzYu/cG5n',
      imageAlt: "RGB Mechanical Keyboard.",
      price: '$129',
      color: 'Black/White',
  },
  {
      id: 6,
      name: 'Laptop Stand',
      href: '#',
      imageSrc: 'https://imgs.search.brave.com/Cw4nAh2s8kslHuBX4Cj529KpYL4bk4Y814TaFKHczrs/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFXNVp5VmFySkwu/anBn',
      imageAlt: "Adjustable Laptop Stand.",
      price: '$39',
      color: 'Silver',
  },
  {
      id: 7,
      name: 'External SSD',
      href: '#',
      imageSrc: 'https://imgs.search.brave.com/A7eQxAQySwTFttHL6m2yc6fBPMCv4aO7XO_1HRb-Hhw/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/MzEydG1YeU5pdkwu/anBn',
      imageAlt: "Portable External SSD.",
      price: '$89',
      color: 'Gray',
  },
  {
      id: 8,
      name: 'Smartwatch',
      href: '#',
      imageSrc: 'https://imgs.search.brave.com/V2illIk5ifCOwcbp_8kwhdhIyVGbT-K8eqihkVbubOo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5jbm4uY29tL2Fw/aS92MS9pbWFnZXMv/c3RlbGxhci9wcm9k/L2dhcm1pbi1mZW5p/eC03LXByb2R1Y3Qt/Y2FyZC1jbm51Lmpw/Zz9jPTE2eDkmcT1o/XzcyMCx3XzEyODAs/Y19maWxs',
      imageAlt: "Smartwatch with fitness tracking.",
      price: '$199',
      color: 'Black',
  },
];
